### ISSUE TITLE
Lost theme custom icon in standalone theme

### ISSUE THREAD

**Issue by decapoda** [parallelus/Runway-Framework#117]
After the extract of a new standalone theme there is an empty space instead of the icon.
![losticon](https://cloud.githubusercontent.com/assets/4149494/6258711/c7768b36-b82f-11e4-89cb-b7de01a96fae.jpg)

Icon itself is in place, in theme's folder (custom-icon.png). Tested with liftoff and my own theme

**Comment by parallelus** [comment]
This was fixed in the development version. I've tested it as recently as last month. Make sure you're using the latest pull from the develop branch.

**Comment by decapoda** [comment]
Yep, I am. I made a fork yesterday and now on develop branch 
And if I haven't used latest develop branch, I couldn't have tested last customizer fixes

**Comment by alexxgermann** [comment]
Seems that this issue appeared when the line  "Icon: .... " was excluded from header in the file style.css - the info about custom icon has been taken from the header. I have fixed this bug and currently for a standalone theme the info about custom icon is taken from the file settings.json

**Comment by decapoda** [comment]
Sweet, thank you! It works.
