### ISSUE TITLE
Bootstrap Starter menu not behaving like demo

### ISSUE THREAD

**Issue by blackandyellowstripes** [parallelus/Runway-Framework#125]
I've noticed the menu is not looking right.

1. The menu ul has a height of 43px instead of 80px like the demo
2. The dropdown has a little triangle thing at the top, unlike the demo
3. The dropdown child pages are blue on hover, not grey like the demo

I realise these may be easy to fix, but I wanted to point it out in case it was symptomatic of a bigger issue.

Is this a bug or is it me?

![menubug](https://cloud.githubusercontent.com/assets/11628198/6799236/ded7c0ba-d20b-11e4-8bb7-b383be0fde52.jpg)

**Comment by parallelus** [comment]
This sounds like it may be a customization. It's also not related to the Runway Framework and will be a theme specific support issue. Please post theme support requests to their individual forums: http://runwaywp.com/support/forum/themes/bootstrap-starter/
