### ISSUE TITLE
$wp_filesystem->get_contents() not working on some set-ups

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Runway-Framework#127]
We've had a handful of Vellum users tell us that after updating to Vellum v1.4+ they can no longer see an <strong>Appearance > Theme Options</strong> menu item, and if they try to manually go to the URL for that admin page they get a "you do not have sufficient permissions to access this page" error message.

I was able to look into this on one customer's server and I found that reverting to the <code>file_get_contents()</code> function in 'framework/includes/options-page-render/load.php' fixed the issue on their server.

See here → http://para.llel.us/support/groups/vellum/forum/topic/cannot-access-theme-options-not-sufficient-access-rights-error/?topic_page=2&num=15#post-70010

<strong>Help Center topics:</strong>
→ http://para.llel.us/support/groups/vellum/forum/topic/no-theme-option-in-vellum-1-4-1-after-update/
→ http://para.llel.us/support/groups/vellum/forum/topic/cannot-access-theme-options-not-sufficient-access-rights-error/
→ http://para.llel.us/support/groups/vellum/forum/topic/problem-with-last-updates-cant-see-theme-options-menu/
→ http://para.llel.us/support/groups/vellum/forum/topic/problem-with-last-updates-cant-see-theme-options-menu/#post-69029

**Comment by parallelus** [comment]
From that Help Center topic, the code specific to the problem:

In the ‘**framework/includes/options-page-render/load.php**‘ file and on **line 29** or thereabouts you’ll see the following chunk of code…

```
$pages = array();
foreach ( $page_files as $page_file ) {
  if ( $page_file != '.' && $page_file != '..' ) {
    //$json = file_get_contents( $pages_dir . $page_file );
    $json = $wp_filesystem->get_contents( $pages_dir . $page_file );
    $pages[] = json_decode( $json );
  }
}
```

The old code (or what you can change it back to)…

```
$pages = array();
foreach ( $page_files as $page_file ) {
  if ( $page_file != '.' && $page_file != '..' ) {
    $json = file_get_contents( $pages_dir . $page_file );
    //$json = $wp_filesystem->get_contents( $pages_dir . $page_file );
    $pages[] = json_decode( $json );
  }
}
```

That seems to solve the problem for everyone experiencing the error. What is unclear is why this is happening. We might have to reach out to the WP core and open a ticket. This could be a bug in the `$wp_filesystem` object.

**Comment by alexxgermann** [comment]
This is happening because on the user's site in wp-config.php for Filesystem by default (or plainly) the method ftpext is set. We can resolve this problem by 2 ways:
1) redefine define('FS_METHOD', 'direct') - for example in the file runway-framework/framework/defaults.php after constants definig block (I prefer this way)
2) check the used method and depending on the result use either  $wp_filesystem->get_contents() or file_get_contents().

**Comment by jeffwalker99** [comment]
Sometimes in their 'wp-config.php' file users have WordPress set to use FTP for writing files (plugins, updates, etc.) because their server's folder/file ownerships are set incorrectly, which means WordPress can't write to the server in the normal way, only via FTP. (Some web hosts can't be moved on this issue, even though they are wrong about it.)

So that may be a reason why a user has FS_METHOD set to "ftpext"?

In which case, I vote for option 2 because forcing direct may simply cause another, different WordPress error?

**Comment by jeffwalker99** [comment]
@alexxgermann 

I've been able to get a customer to check this fix, and I've also double checked this myself on that customer's website. FS_METHOD was set to "ftpext" in their 'wp-config.php' file, but unfortunately setting FS_METHOD to "direct" in 'wp-config.php' makes no difference at all.

On my own servers I can replicate the exact problem, all the same symptoms, by setting FS_METHOD to "ftpext", but on this customer's server changing the value makes no difference.

**Comment by alexxgermann** [comment]
I have added the filter which changes Filesystem method, which allows to do without correcting wp-config.php, and have tested it for various variants  FS_METHOD in wp-config.php ( not sat, direct, ftpext ) - everything works properly. @jeffwalker99 Could you please ask your user to test this variant on the server.

**Comment by jeffwalker99** [comment]
@alexxgermann I just tested this myself on the problem server. It works. Awesome!
