### ISSUE TITLE
Putting a php.ini file in the 'framework/libs' folder causes a PHP error

### ISSUE THREAD

**Issue by jeffwalker99** [parallelus/Runway-Framework#130]
If you put a 'php.ini' file in the 'framework/libs' folder it causes a 'headers already sent' PHP error...

<pre>
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /xxx/xxx/xxx/parallelus-vellum/wp-content/themes/parallelus-vellum/framework/libs/php.ini:5) in /xxx/xxx/xxx/parallelus-vellum/wp-content/themes/parallelus-vellum/extensions/contact-fields/inc/functions.php on line 3
</pre>

...because the theme is outputting the contents of the 'php.ini' file.

**Comment by jeffwalker99** [comment]
It doesn't seem to like a '.DS_Store' file in there either...

<pre>Bud1sbuild @€ @€ @€ @formsbuilderbwspblobøbplist00Ù	 ]ShowStatusBar[ShowSidebar[ShowPathbar[ShowToolbar[ShowTabView_ContainerShowSidebar\WindowBounds\SidebarWidth_PreviewPaneVisibility		_{{17, 74}, {972, 1343}}¯)5AMYp}Š¢£¤¥¦§¨ÂÄÅformsbuilderlsvPblobobplist00Ø	D F_viewOptionsVersion_showIconPreview_calculateAllSizesWcolumnsXtextSizeZsortColumn_useRelativeDatesXiconSize	ª $).38=Ô ZidentifierUwidthYascendingWvisibleTname“	Ô \dateModifiedµ	Ô[dateCreatedÔ ! Tsizea	Ô%& Tkinds	Ô*+ Ulabeld	Ô/0 WversionK	Ô45 Xcomments,	Ô9:^dateLastOpenedÈÔ>?@CWvisibleUwidthYascendingYdateAdded#@(	#@0.@T\epƒŒŽ›¤¯µ¿ÇÌÏÐÑÚçéêëô"$%&/5789BJLMNW`cden}€Š’˜¢£¤®·¸GÁformsbuilderlsvpblobWbplist00Ø	E G_viewOptionsVersion_showIconPreview_calculateAllSizesWcolumnsXtextSizeZsortColumn_useRelativeDatesXiconSize	Ù $).38=BXcomments^dateLastOpened[dateCreatedTsizeUlabelTkindWversionTname\dateModifiedÔ UindexUwidthYascendingWvisible,	Ô !ÈÔ%&µÔ*+ a	Ô/0 d	Ô45 s	Ô9: K Ô>? “	Ô	& 	#@(	#@0.@T\epƒŒŽ£¬»ÇÌÒ×ßäñú(*,-.79;<=FHJKLUWYZ[dfhijsuwxy‚„‡ˆ‰’“”žH§EDSDB `€ @€ @€ @isible,	Ô !ÈÔ%&µÔ*+ a	Ô/0 d	Ô45 s	Ô9: K	Ô>? “	Ô	& 	#@(	#@0.@T\epƒŒŽ£¬»ÇÌÒ×ßäñú(*,-.79;<=FHJKLUWYZ[dfhijsuwxy‚„‡ˆ‰’“”žH§
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /xxx/xxx/xxx/parallelus-vellum/wp-content/themes/parallelus-vellum/framework/libs/.DS_Store:38) in /xxx/xxx/xxx/parallelus-vellum/wp-content/themes/parallelus-vellum/extensions/contact-fields/inc/functions.php on line 3</pre>

**Comment by jeffwalker99** [comment]
I'm wondering how many more folders there might be that are going to barf at the presence of a 'php.ini' and/or a '.DS_Store' file?

**Comment by parallelus** [comment]
There are some folders in the framework that read the files inside an attempt to load them automatically. This is how the extensions and data-types work, like WP plugins, to be automatically recognized and loaded. We should modify the function to only recognize files with the `.php` extension and it will probably take care of these problems.
