### ISSUE TITLE
Container type "show/hide" not remembering visibility in Theme Options Pages

### ISSUE THREAD

**Issue by parallelus** [parallelus/Runway-Framework#132]
When using a container on an options page of the type "Show / hide" is expanded and collapsed, the state of that container (in the theme options page) is not being saved. 

##### Setting in Options Builder
![image](https://cloud.githubusercontent.com/assets/1123420/7140675/3be2e6fe-e292-11e4-86a2-7aa0b6171483.png)

This means, that when working on the theme options and expanding a container to edit a value, after saving the page the container will be collapsed again. The user must expand that container, and any others they previously expanded, before viewing or editing an option inside them.

##### Expanded by user while editing
![image](https://cloud.githubusercontent.com/assets/1123420/7140769/ddeee498-e292-11e4-9e6f-159ddc488838.png)

##### Before and after saving in theme options pages, reverts to closed
![image](https://cloud.githubusercontent.com/assets/1123420/7140908/cc6b87de-e293-11e4-9b44-a21ab436b9a0.png)

We need to track those expand/collapse states (just like we're doing in the Options Builder) for the user to make it a bit easier on them. It feels natural for the container state to be remembered and it's a default across most of the WP admin. This will add consistency to the interface matching the expectations of the user from the behavior of other WP admin areas.

-----

### Cursor showing drag on theme options pages
![image](https://cloud.githubusercontent.com/assets/1123420/7140788/01f52d8e-e293-11e4-96d5-f151488adc4a.png)

One other small issue is the cursor on hovering. On the theme options pages the items cannot be dragged so we need to show the default cursor. **This should only apply to the *Theme Options Pages* hover state.** The behavior in the *Options Builder* should not be altered.

**Comment by lesninsky** [comment]
I could not reproduce this issue - in the version runway-framework from  html-2-wp branch the changing of Container type on "show-hide" is properly saved and applied to panels (collapsed/expanded). Could you please check write rights for json-files for option-pages?

**Comment by parallelus** [comment]
It was probably another side effect of the notices that were showing from the custom plugin being created. 

Please change the move cursor to show 'default' instead and we can close this issue.
