### ISSUE TITLE
font-select-type.php

### ISSUE THREAD

**Issue by MrAhmad** [parallelus/Runway-Framework#137]
hi All 

i had download the framework, and generate the child theme liftoff. 

after that i download this theme as standalone, then i upload to my website.

there is a fatal error shown when chose to customize the theme

fatal error call to undefined function runway_admin_themes_list_prepare in font-select-type.php line 64. and the customize panel freeze and shown white page

**Comment by parallelus** [comment]
I think I saw this while developing our latest theme. I pushed some updates related to the error, but they would only be on the 'develop' branch right now. 

You can download the Runway develop branch here: https://github.com/parallelus/Runway-Framework/archive/master.zip

While it is called 'develop' this is a pretty stable release. We've used it for our own development and themes that are being published and sold, so we have done lots of testing and have confidence in the code being used on production environments. It's probably ready for a push to the 'master' for a new release.

**Comment by MrAhmad** [comment]
thank you , i will try and update you

**Comment by MrAhmad** [comment]
hi dear , its same error, when  i use link which you gave to me,

fatal error call to undefined function runway_admin_themes_list_prepare in font-select-type.php line 64.

i think this function not defined in file 

$t = runway_admin_themes_list_prepare( $current_theme );

**Comment by parallelus** [comment]
Just to confirm, you updated the entire install of Runway from the 'develop' branch, not just the data type for the font picker?

In the standalone theme, do you have the folder `framework/includes/themes-manager/`, or is that being deleted? The definition for this function is included in the file "**framework/includes/themes-manager/settings-object.php**" on **line 876**.

**Comment by MrAhmad** [comment]
The full branch. I will check the stand alone if have or not

**Comment by MrAhmad** [comment]
hi dear, i have to confirm in the standalone theme , the following folders not included 
framework/includes/themes-manager/
framework/includes/dashboard/
framework/includes/downloaded-directory/
framework/includes/themes-manager/
framework/includes/report-manager/

**Comment by parallelus** [comment]
You're not using the full 'develop' branch. We updated it a while back to keep the "**includes/themes-manager**" folder. If that is being deleted you have an older version.

See this commit for details: 24959ce29705f9eddf18364fe0cff9ee767cdac0

Copying that folder back to your standalone will get rid of the error.

**Comment by MrAhmad** [comment]
thank you, solved
