### ISSUE TITLE
Error on delete child themes

### ISSUE THREAD

**Issue by Danjavia** [parallelus/Runway-Framework#141]
Please replace it on  runway-framework\framework\includes\themes-manager\views\del-packages-confirmation-all.php.

    <?php echo esc_url( $developer_tools->self_url('do-package').'&name='.$name.'&action=delete-package-all&package=all'; ) ?> ON LINE 9

for this:

    <?php echo esc_url( $developer_tools->self_url('do-package').'&name='.$name.'&action=delete-package-all&package=all' ); ?> ON LINE 9

    
and this 

    <?php echo esc_url() $developer_tools->self_url('do-package').'&name='.$name; ) ?> ON line 10

for:

    <?php echo esc_url( $developer_tools->self_url('do-package').'&name='.$name ); ?> ON line 10

**Comment by kermage** [comment]
Also on **runway-framework\framework\includes\themes-manager\views\del-packages-confirmation.php**

Lines:
```
8) <?php echo esc_url( admin_url('admin.php?page=themes&navigation=delete-theme&name='.$del_theme_info['Folder'].'&confirm=true'); ) ?>
9) <?php echo esc_url( admin_url('admin.php?page=themes'); ) ?>
```
to:
```
8) <?php echo esc_url( admin_url('admin.php?page=themes&navigation=delete-theme&name='.$del_theme_info['Folder'].'&confirm=true') ); ?>
9) <?php echo esc_url( admin_url('admin.php?page=themes') ); ?>
```

**Comment by parallelus** [comment]
Thanks for reporting these. We'll have them updated.
