### ISSUE TITLE
problems with wordpress 4.3rc1

### ISSUE THREAD

**Issue by lilmike** [parallelus/Runway-Framework#143]
Hi,
I was trying out runway with my development copy of wordpress (4.3rc1). I noticed a few things:
1. The extensions manager just shows the checkboxes (which still work) to select the extensions, nothing about them or an activate link or anything.
2. The layout manager does not show the list of layouts to edit or delete once one is created, it only shows the places to assign layouts to different types of pages.
3. The problem with the layout manager is possibly a problem with the sidebars manager as well, I'm unsure on that one.
Anyway, I just figured I'd post here and give you a link to the wordpress.org forum topic I opened to see if it was wordpress's fault or runway's (I'm thinking it could be wordpress's, as it works fine in 4.2.3).
https://wordpress.org/support/topic/tables-with-options-similar-to-the-plugin-manager-are-not-working-in-latest-43
Thanks,
-Michael.

**Comment by parallelus** [comment]
I've been using the nightly releases of WP and haven't noticed these things but we will take a close look and see what's happening. Sometimes it can be as simple as a new version of WP using a different jQuery library or another odd thing such as that where it results in a conflict.

What version of Runway are you using?

**Comment by parallelus** [comment]
I've just tested with WP 4.3-RC1-33527 on my local and didn't see any of the problems you were describing. Can you try a fresh install? It might be the child theme activated is causing a conflict rather than the framework. If you can activate another child theme that will be very useful information too.

When I have debug mode enabled I'm seeing the notice below, however this shows up even using the WP default themes so it seems to not be Runway causing it. It could be one of the plugins I have active. I didn't test disabling all plugins.

> Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! 
> Use __construct() instead. in C:\xampp\htdocs\test\wp-includes\functions.php on line 3457

When the notice is showing in the admin it causes many of the JavaScript actions in Runway to fail. I couldn't save a new layout until the debug mode was set to `FALSE`. That's sure to be fixed in the final release.

Any additional details you can share will help us. Since we're not seeing the issue and we have no other reports I'm going put this issue on hold until we have more details. Thanks!

**Comment by lilmike** [comment]
Hi,
I've (at least tried to) make a screenshot showing one of the issues. It's attached, and I don't think it's the theme -- it's just the default almost empty theme that runway creates for you when you hit add theme. I don't think it could be plugins either, in fact I don't think I have any plugins activated (just like on the 4.2.3 site). Are you running the 4.3 nightly or the 4.2.4 nightly? Just curious, as this doesn't happen on my 4.2.3 site (haven't checked 4.2.4 nightly) but it does happen on 4.3 nightlies.
Thanks,
-Michael.
![screenshot-problem](https://cloud.githubusercontent.com/assets/1117427/9045607/ffac3bcc-39e9-11e5-97b0-d2fdd039cad9.png)

**Comment by parallelus** [comment]
I tested with the 4.3 nightly.

**Comment by lilmike** [comment]
Did the screenshot show the checkboxes, but without all the other 
details? I just ask because I'm unsure if I took a screenshot of the 
proper part of the page -- sometimes my screen reader can be off on a 
part of the page that isn't actually on the screen.
-Michael.

**Comment by parallelus** [comment]
Yes, that's what the screenshot shows. It's a blank content area with checkboxes.

**Comment by parallelus** [comment]
I don't think this will matter, but could you try the develop branch of Runway: https://github.com/parallelus/Runway-Framework/archive/develop.zip

**Comment by lilmike** [comment]
Hi,
Nope, that didn't do anything different. Is there perhaps some 
functionality of WordPress you're using in all of those cases (list of 
layouts in the layout manager, list of sidebars in the sidebars manager, 
and extensions) that I may be able to see if any other plugin/theme has 
the same problems?
-Michael.

**Comment by parallelus** [comment]
What's odd to me is that the content isn't being included. If it was a styling issue that would make more sense but a lack of content is very confusing. The output is a simple table output, just like plugin or post lists in the admin:

Example from the sidebars extension _sidebars/views/admin-home.php_
```
<br/>
<?php if(!empty($sidebars)): ?>
		<table class="wp-list-table widefat">
			<thead>
				<tr>
					<!-- <th scope="col" id="cb" class="manage-column column-cb check-column" style="width: 0px;"></th> -->
					<th id="field-name" class="manage-column column-name"><?php _e('Name', 'framework') ?></th>
					<th id="field-alias" class="manage-column column-alias"><?php _e('Alias', 'framework') ?></th>
					<th id="field-shortcode" class="manage-column column-shortcode"><?php _e('Shortcode', 'framework') ?></th>
					<th id="field-description" class="manage-column column-description"><?php _e('Description', 'framework') ?></th>
					<th id="field-actions" class="manage-column column-actions"><?php _e('Actions', 'framework') ?></th>
				</tr>
			</thead>
			<tbody id="the-list">
				<?php foreach ($sidebars as $key => $values): ?>
					<tr class="active">
						<td class="column-title">
							<p><strong><?php rf_e($values['title']); ?></strong></p> 
						</td>
						<td class="column-alias">
							<p><?php echo  $values['alias']; ?></p>
						</td>
						<td class="column-shortcode">
							<p>[sidebar alias="<?php echo  $values['alias']; ?>"]</p>
						</td>
						<td class="column-description">
							<p><?php rf_e($values['description']); ?></p>
						</td>
						<td class="column-description">
							<p>
								<a href="<?php echo esc_url( $this->self_url('edit-sidebar') .'&alias='. $values['alias'] ); ?>"><?php _e('Edit', 'framework') ?></a> | 
								<a style="color: #BC0B0B;" href="<?php echo esc_url( $this->self_url() .'&action=delete-sidebar&alias='. $values['alias'] ); ?>"><?php _e('Delete', 'framework') ?></a>
							</p>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
<?php else: ?>
<h3><?php _e('No custom sidebars have been created yet.', 'framework') ?></h3>
<?php endif; ?>
```

**Comment by lilmike** [comment]
Yeah, that is confusing. The first time I did it it looked like my 
layout may have been created improperly, but now I'm unsure. I'm going 
to try to get a friend to install runway on his dev machine to see if he 
has the same issues, but for now, here's the steps I follow just in case 
there's some inconsistancy in how things are happening:
1. Download and install 4.3rc1.
2. copy runway-framework to the themes directory and also copy the 
extensions (I did all of them) over to the runway-framework/extensions 
directory.
3. In WordPress admin, navigate to themes, then activate runway.
4. Note at this point one time I saw a prompt to install the liftoff 
theme as a getting started guide, but I don't seem to see this anymore 
(or maybe I'm just missing it). In any case, click create new theme.
5. Enter a name, and leave everything else either default or blank.
6. Click create.
7. Note at this point if you go to runway>extensions I see a table with 
7 checkboxes (one each for the 6 extensions and one for select all), but 
nothing else.
Hth,
-Michael.

**Comment by lilmike** [comment]
Hi,
I just saw this post on the make WordPress core blog. Perhaps this has something to do with the breakage? https://make.wordpress.org/core/2015/08/08/list-table-changes-in-4-3/
-Michael.

**Comment by parallelus** [comment]
Possibly. I didn't test reducing the screen size and that could be what is happening. 

@alexxgermann Could you take a look at this post and do a bit of testing to see if the 4.3 smaller responsive screen display is impacting Runway in this area?  https://make.wordpress.org/core/2015/08/08/list-table-changes-in-4-3/

Thanks!

**Comment by alexxgermann** [comment]
I confirm there is an issue for responsive mode. It occurs because we do not use WP_List_Table functionality to display records in exеensions (Extension manager, Layouts manager etc.), on which the new features are based. I also tested these changes for displaying destinations in Destination plugin where this functionality is used - everything works correctly.
