### ISSUE TITLE
Theme options pages not working with altered WP admin folder permissions.

### ISSUE THREAD

**Issue by parallelus** [parallelus/Runway-Framework#146]
We have a report of a problem with theme admin menus not appearing, missing menu icons and other theme options specific weirdness on installs where the `wp-admin` directory has modified permissions. 

The report spcifies the issue happenes when following the instructions for hardening the directory permsssions of the `wp-admin` directory as described here: https://codex.wordpress.org/Hardening_WordPress#File_Permissions

The framework makes no specific call to write to the admin directory. It's not needed but it's possible we're seeing a side effect of another feature. Possibly there is a check for this permission or another feature is calling upon a file located in the wp-admin directory to perform a task and as a result it's a cascading permission issue? It will require some exploring to figure out.

The details from the user are posted here: http://runwaywp.com/support/topic/fresh-install/

**Comment by 802i** [comment]
Any update on this?

**Comment by parallelus** [comment]
We had two developers out at the same time last week so nobody had a chance to look at it during that time. We are looking into it and will post when we know more.

**Comment by 802i** [comment]
Just looking for some update here, possibly we missed a new release that negates this?

**Comment by lesninsky** [comment]
I made the fresh install of Runway Framework. Apache has been ran as www-data user. The owner of the wp-admin folder is a user account with 755 rights (according https://codex.wordpress.org/Hardening_WordPress#File_Permissions). Also user account is the owner for wp-admin/includes/file.php. I have found no errors or side effects during testing and everything works normally.

**Comment by parallelus** [comment]
I believe this was resolved by another fix. Closing the issue for now.
