### ISSUE TITLE
Odd error after installing Runway Framework

### ISSUE THREAD

**Issue by ladycodemonkey** [parallelus/Runway-Framework#152]
I installed Runway Framework and I am getting the following error message in the back end:

Illegal string offset 'Icon' in in /home/digitald/public_html/mig/wp-content/themes/runway/framework/includes/load-functions.php on line 608

Line 608 in load-functions.php reads:

$icon = $settings['Icon'];

Best,

Cynthia

**Comment by parallelus** [comment]
This is fixed in the 'develop' branch, see reference: https://github.com/parallelus/Runway-Framework/pull/144

You can download the develop branch here: https://github.com/parallelus/Runway-Framework/archive/develop.zip
