### ISSUE TITLE
Optionbuilder light boxalign on right

### ISSUE THREAD

**Issue by woutervdpol** [parallelus/Runway-Framework#157]
When i click on edit in the option builder i get the lightbox but all content in in the right corner so i cant read anything.

![example](https://cloud.githubusercontent.com/assets/6317410/12222574/75c2fd4c-b7c0-11e5-82b8-7953b271af2c.PNG)

**Comment by parallelus** [comment]
I was never able to replicate this. It's most likely a plugin loading a custom styled version of jQuery UI. If they did not scoping the enqueue to only include the CSS and JS on the plugin specific pages it would conflict with any other area of the admin using the same library.
