### ISSUE TITLE
List menu are wrong display after setting sort menu

### ISSUE THREAD

**Issue by minhcanhdn** [parallelus/Runway-Framework#159]
I set menu orders in menu setings but it still not work.

**Comment by parallelus** [comment]
I'm not understanding what you're posting. If it's about a specific theme rather than the framework core, please open a topic on our forums: http://runwaywp.com/support

**Comment by minhcanhdn** [comment]
![screenshot-lacathemes local 2016-01-26 14-31-49](https://cloud.githubusercontent.com/assets/136077/12574816/fb03cd44-c439-11e5-8089-dba63431f2cd.png)
![screenshot-lacathemes local 2016-01-26 14-33-03](https://cloud.githubusercontent.com/assets/136077/12574817/fb2d1384-c439-11e5-91b2-d080b63e8f78.png)

Sorry, Please see the images
