### ISSUE TITLE
Font-selector: Fonts not loading

### ISSUE THREAD

**Issue by PsySolix** [parallelus/Runway-Framework#161]
Hi everyone, 

I'm loving the Runway Framework, very solid and it just works as intended. Speeding up development time of WP themes a bunch!

Now I do have encountered a bug, but don't seem to find information about it on the issues here or the trusted Google ;-) 

**The Problem**
I have multiple Font selector fields, so a user can change each font-family and size etc.
Now when I choose a font that I dont have installed. Say 'Lobster' (a google font)
It doesn't load. None of the google fonts load.. It just renders as a serif font. 

![image](https://cloud.githubusercontent.com/assets/6713256/13076310/cd96952a-d4b1-11e5-9c9a-845666f43461.png)

**What I tried**
- Loading google fonts through a plugin -> didn't work. 
- Tinkering around the data-type/font-select.php file -> didn't work. 

So my fellow developers, what can I do to fix this? 

Greetings!

**EDIT**
I found my own temporary solution, I'll post it here so others can try to improve the solution or even use it as is ;)

![image](https://cloud.githubusercontent.com/assets/6713256/13079149/10c41302-d4c3-11e5-8d9f-1e90ef6b0727.png)

**EDIT v2**
Hi there, I improved the code not importing duplicates.
The above EDIT is abundant! This is much better solution! I still need to find an automatic way for getting font selector fields. For now I manually add them to $font_arrayz.
![image](https://cloud.githubusercontent.com/assets/6713256/13104782/93b18d48-d55f-11e5-9cf1-79f663230aa0.png)

**Comment by parallelus** [comment]
Thanks for this. We plan to make the fonts render in the admin for the font select.
