### ISSUE TITLE
Translation strings updates for variables.

### ISSUE THREAD

**Issue by parallelus** [parallelus/Runway-Framework#166]
We need to convert these instances of the translation strings to use `sprintf()` or a similar function which plugs variables into a string:
1. https://github.com/parallelus/Runway-Framework/blob/master/runway-framework/framework/includes/report-manager/settings-object.php#L73
2. https://github.com/parallelus/Runway-Framework/blob/master/runway-framework/framework/includes/report-manager/settings-object.php#L78

**Comment by alexxgermann** [comment]
Please see next commits:
https://github.com/parallelus/Runway_Extensions/commit/86fceeba57b26e59d4d932c9d8fa9a5138838315 (Contact-fields and Extensin Server)
https://github.com/parallelus/Layout-Manager-for-Runway/commit/3f1c48b7b1f7b25b0f34c6ab0ee2307c779fdbf3 (Layout manager)
https://github.com/parallelus/Plugin-Installer-for-Runway/commit/06f70cae6578f8afab55c38ea8feef7024b8a770 (Plugin installer)

**Comment by alexxgermann** [comment]
@parallelus I have noticed that in some extensions text domain "framework" has not been changed to "runway". Should I replace this ?

**Comment by parallelus** [comment]
Yes, as we work on these extensions we can update the translation text domains.

**Comment by alexxgermann** [comment]
Updated translation text domain from 'framework' to 'runway' for

Contact-fields, commit - https://github.com/parallelus/Runway_Extensions/commit/3e894a83435f47ddd673c782be83b76dd9c1db30
Custom-branding, commit https://github.com/parallelus/Runway_Extensions/commit/cabc1038ec5927aaf9cb7fcc5c19e64fbb02d1a6
Extensions-server, commit https://github.com/parallelus/Runway_Extensions/commit/61f50085278675aa213674e6bce75c1a33ae56f3
Help-tabs, commit https://github.com/parallelus/Runway_Extensions/commit/26a0cf31c137369f3df358731012f676ccabfe11
Polls, commit https://github.com/parallelus/Runway_Extensions/commit/9d4cacae6bbfd4ce663911d4785fcc84f7d2a21c

**Comment by alexxgermann** [comment]
Please see commit https://github.com/parallelus/Plugin-Installer-for-Runway/commit/a13118667daae04aba9c5729654a152e2f969941 too.

**Comment by alexxgermann** [comment]
Please see commit https://github.com/parallelus/Runway_Extensions/commit/60896edb23482b84773158df8d6543aff4a87edf
