### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by 360path** [parallelus/Runway-Framework#215]
It seems that development on the framework has halted. Has the project been abandoned?

**Comment by heyflorin** [comment]
Curious to know this as well. Looking for this as a possible framework for a few upcoming projects.

**Comment by parallelus** [comment]
We have been busy on other projects. Right now there isn't any time scheduled for making additions to the framework but we will continue to try and manage bugs and other fixes as needed. 

Thanks!
