### ISSUE TITLE
Runway Framework updates

### ISSUE THREAD

**Issue by echostorm** [parallelus/Runway-Framework#216]
I would like to ask if Runway is still a viable framework for wordpress theme development? I ask because im concerned with compatibility with new Wordpress features and plugins etc since 2017, for example Gutenberg editor but what im really worried about is it seems there have been no commits or updates since  Jan, 2017! Is Runway framework still a good secure option for theme development?

**Comment by parallelus** [comment]
We're still using it for lots of themes. It's been stable for us for a long time. We haven't been developing new themes recently which is why Runway hasn't been updated. Theme development for us usually coincides with updating the framework. There aren't currently any plans for updates right now.
